name: Publish Docker Image

on:
  push:
    branches: [ main ]
  release:
    types:
      - published

jobs:

  build:
    if: "!containers(githhub.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/shrutir/rgapi
          tag-sha: true
          tag-edge: true
          tag-latest: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
